<?php
/**
 * @category   MageTornado
 * @package    MageTornado_EmailSignature
 * @author     prajapatirakesh03@gmial.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace MageTornado\EmailSignature\Model\ResourceModel\EmailSignature;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'emailsignature_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'MageTornado\EmailSignature\Model\EmailSignature',
            'MageTornado\EmailSignature\Model\ResourceModel\EmailSignature'
        );
    }
}